"""Build one self-contained JSONL document per terminology item.

The source file is intentionally human-editable. The generated JSONL follows
the common {id, content, metadata} shape used by LangChain, LlamaIndex and
custom pgvector ingestion jobs. Embeddings are generated by the application,
not checked into this repository.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "source" / "terminology.json"
DATA = ROOT / "data"


CATEGORY_DEFAULTS = {
    "goods_type": {
        "target": "商品类型",
        "three_d": "将它解释为一个可独立展示、结构清晰的谷子商品模型，优先保证轮廓、分件和展示方式明确。",
        "preview": "将它表现为真实可售卖的二次元周边，突出商品轮廓、材质、工艺和陈列方式。",
        "negative": ["无关的其他商品类型", "不可辨认的抽象物体"],
    },
    "character_concept": {
        "target": "角色与人设",
        "three_d": "保持角色身份、标志性特征、服装和配色的一致性，适合继续制作角色展示模型。",
        "preview": "将角色作为商品主视觉，保持人设识别点清晰，避免被背景、道具或文字遮挡。",
        "negative": ["角色身份漂移", "随机改变发色或服装", "OOC表现"],
    },
    "appearance": {
        "target": "外貌特征",
        "three_d": "把该特征建成清晰、可见、与主体连接合理的几何或材质细节。",
        "preview": "在角色预览图中明确表现该特征，保证轮廓和识别细节可见。",
        "negative": ["特征缺失", "特征被头发或配件遮挡", "左右结构无意不对称"],
    },
    "fashion": {
        "target": "服装与题材",
        "three_d": "将服装拆解为合理的分层、褶皱、扣件和配件，避免布料与身体发生明显穿插。",
        "preview": "使用明确的服装轮廓、面料质感和题材配色，让风格一眼可辨。",
        "negative": ["服装结构混乱", "随机增加不相干的服饰", "严重穿模"],
    },
    "visual_style": {
        "target": "画风与视觉语言",
        "three_d": "将二维视觉语言转译为可执行的模型比例、材质、着色和灯光设置。",
        "preview": "将画风落到线条、色块、光影、比例、材质和背景，而不是只使用宽泛的风格词。",
        "negative": ["风格混杂", "写实皮肤纹理", "不匹配的摄影风格"],
    },
    "composition": {
        "target": "构图与姿态",
        "three_d": "遵循指定视角或姿态，保留完整轮廓，并让模型适合旋转检查。",
        "preview": "使用指定镜头和陈列构图，确保商品主体完整、无遮挡且有可读的空间层次。",
        "negative": ["裁切主体", "遮挡关键部件", "畸变透视", "重复肢体"],
    },
    "model_3d": {
        "target": "3D技术约束",
        "three_d": "把该技术要求作为模型生成、清理、导出和后处理的硬约束。",
        "preview": "在预览中真实反映模型的结构、材质和制造约束，不用视觉效果掩盖几何错误。",
        "negative": ["开口网格", "自相交", "悬浮几何体", "不可制造的薄片", "破面"],
    },
    "material_process": {
        "target": "材质与商品工艺",
        "three_d": "使用可区分的材质分区、厚度和边缘结构表现该工艺，避免把印刷效果误当成几何。",
        "preview": "用正确的反射、透光、粗糙度、纹理和局部高光表现商品工艺。",
        "negative": ["材质认错", "塑料感过强", "过曝高光", "工艺细节缺失"],
    },
}


def slug(term: str) -> str:
    """Stable key: adding or reordering source items must not change an ID."""
    return hashlib.sha1(term.encode("utf-8")).hexdigest()[:8]


def compact_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def build() -> tuple[int, str]:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    DATA.mkdir(parents=True, exist_ok=True)

    documents: list[dict] = []
    categories: list[dict] = []
    global_index = 0

    for group in source["groups"]:
        category = group["category"]
        defaults = CATEGORY_DEFAULTS[category]
        categories.append({
            "category": category,
            "subcategory": group["subcategory"],
            "item_count": len(group["items"]),
        })
        for item_index, item in enumerate(group["items"], start=1):
            global_index += 1
            term = item["term"]
            aliases = item.get("aliases", [])
            tags = item.get("tags", [])
            alias_text = "、".join(aliases)
            tag_text = "、".join(tags)
            definition = item["definition"].rstrip("。！？")
            content = (
                f"术语：{term}\n"
                f"类别：{group['subcategory']}（{category}）\n"
                f"别名：{alias_text}\n"
                f"定义：{definition}。\n"
                f"标签：{tag_text}\n"
                f"3D生成用法：{defaults['three_d']}\n"
                f"预览图用法：{defaults['preview']}"
            )
            prompt_3d = f"{term}；{definition}。{defaults['three_d']}"
            prompt_preview = f"{term}；{definition}。{defaults['preview']}"
            negative = list(dict.fromkeys(defaults["negative"] + item.get("negative_terms", [])))
            doc = {
                "id": f"anime.{category}.{slug(term)}",
                "content": content,
                "metadata": {
                    "schema_version": "1.0.0",
                    "knowledge_version": source["version"],
                    "language": source["language"],
                    "domain": source["domain"],
                    "term": term,
                    "aliases": aliases,
                    "category": category,
                    "subcategory": group["subcategory"],
                    "tags": tags,
                    "prompt_targets": ["text_to_3d", "preview_image"],
                    "retrieval_keywords": [term, *aliases, *tags],
                    "prompt_fragments": {
                        "text_to_3d": prompt_3d,
                        "preview_image": prompt_preview,
                        "negative": negative,
                    },
                    "related_terms": [],
                    "risk_tags": item.get("risk_tags", []),
                    "source": "source/terminology.json",
                },
            }
            documents.append(doc)

    jsonl = "".join(compact_json(doc) + "\n" for doc in documents)
    output = DATA / "terms.jsonl"
    output.write_text(jsonl, encoding="utf-8", newline="\n")
    checksum = hashlib.sha256(jsonl.encode("utf-8")).hexdigest()

    (DATA / "categories.json").write_text(
        json.dumps({"knowledge_version": source["version"], "categories": categories}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (DATA / "manifest.json").write_text(
        json.dumps({
            "schema_version": "1.0.0",
            "knowledge_version": source["version"],
            "document_count": len(documents),
            "embedding_status": "not_generated",
            "embedding_instruction": "由运行时使用项目统一 embedding 模型生成，不要把向量提交到词库文件。",
            "terms_sha256": checksum,
            "built_at_utc": datetime.now(timezone.utc).isoformat(),
        }, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return len(documents), checksum


if __name__ == "__main__":
    count, checksum = build()
    print(f"built {count} documents; sha256={checksum}")
